repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.11
        args: [--line-length=100]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black, --multi-line=3, --trailing-comma, --line-width=100]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.7.10, flake8-comprehensions==3.12.0]
        args: [--max-line-length=100, --ignore=E203, --max-complexity=10]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil, types-pyyaml]
        args: [--ignore-missing-imports, --disallow-untyped-defs, --strict-equality, --warn-return-any, --warn-unused-configs, --show-error-context, --show-column-numbers, --show-error-codes, --no-pretty, --no-error-summary]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g.: [feat, fix, ci, chore, test]
