# Cloud Build configuration for deploying to Cloud Run with Secret Manager

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8  # More CPU for faster builds
  diskSizeGb: 100  # Larger disk for build cache
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'REGION=us-central1'
  - 'SERVICE_NAME=photoportfolio-backend'
  - 'GCS_BUCKET=photoportfolio-uploads'
  - 'DB_INSTANCE=photoportfolio-db'
  - 'DB_REGION=us-central1'
  - 'PYTHONPATH=/workspace/backend'

# Grant the Cloud Build service account access to Secret Manager
substitutions:
  _SERVICE_ACCOUNT: ${_SERVICE_ACCOUNT}
  _SECRETS_ENV: _SECRETS_ENV

# Give the Cloud Build service account access to the secrets
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/database-credentials/versions/latest
    env: 'DB_CREDENTIALS'
  - versionName: projects/$PROJECT_ID/secrets/app-secret-key/versions/latest
    env: 'APP_SECRET_KEY'

steps:
  # Install dependencies and run tests
  - name: 'python:3.12-slim'
    id: 'test'
    entrypoint: 'bash'
    dir: 'backend'
    args:
      - '-c'
      - |
        set -e
        pip install -r requirements.txt -r requirements-dev.txt
        python -m pytest tests/ -v --cov=app --cov-report=xml:coverage.xml --cov-report=term-missing
        # Fail the build if coverage is below 80%
        python -c \
          "import xml.etree.ElementTree as ET; \
          tree = ET.parse('coverage.xml'); \
          cov = float(tree.getroot().attrib.get('line-rate', 0)) * 100; \
          print(f'Coverage: {cov:.2f}%'); \
          assert cov >= 80.0, f'Coverage {cov:.2f}% is below required 80%'"
    env:
      - 'ENVIRONMENT=test'
      - 'TESTING=true'
      - 'PYTHONPATH=/workspace/backend'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    dir: 'backend'
    args:
      - 'build'
      - '--network=cloudbuild'
      - '-t'
      - 'gcr.io/$PROJECT_ID/photoportfolio-backend:latest'
      - '.'
    waitFor: ['-']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/photoportfolio-backend:latest'
    waitFor: ['build']

  # Deploy the container to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    secretEnv: ['DB_CREDENTIALS', 'APP_SECRET_KEY']
    args:
      - '-c'
      - |
        # Parse database credentials from secret
        DB_CREDS_JSON="$$DB_CREDENTIALS"
        
        # Deploy the service with secrets
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --service-account=photo-portfolio-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --add-cloudsql-instances=$PROJECT_ID:$DB_REGION:$DB_INSTANCE \
          --set-secrets=DB_CREDENTIALS=$$DB_CREDENTIALS:latest,APP_SECRET_KEY=$$APP_SECRET_KEY:latest \
          --set-env-vars=\
            USE_SECRET_MANAGER=true,\
            GOOGLE_CLOUD_PROJECT=$PROJECT_ID,\
            GCS_BUCKET=$GCS_BUCKET \
          --cpu=2 \
          --memory=2Gi \
          --concurrency=80 \
          --timeout=300s \
          --min-instances=1 \
          --max-instances=10 \
          --ingress=all \
          --vpc-egress=all \
          --labels=app=photoportfolio,component=backend,managed-by=cloud-build \
          --quiet
    waitFor: ['push']

# Timeout for the entire build
timeout: 1200s  # 20 minutes

# Configure build tags
tags:
- 'photoportfolio'
- 'backend'
- 'cloud-run'
