[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  GCS_BUCKET = "photoportfolio-uploads"
  DB_INSTANCE = "photoportfolio-db"
  DB_NAME = "photoportfolio"
  DB_USER = "rlust"
  DB_PASSWORD = "Rc514131!"
  DB_REGION = "us-central1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google-cloud/storage"]

[dev]
  command = "flask run --port=8888"
  targetPort = 8888
  publish = "."
  port = 8888
